// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom';

export const json = [{
  "breeds": [
    {
      "weight": {
        "imperial": "5 - 10",
        "metric": "2 - 5"
      },
      "id": "acur",
      "name": "American Curl",
      "cfa_url": "http://cfa.org/Breeds/BreedsAB/AmericanCurl.aspx",
      "vetstreet_url": "http://www.vetstreet.com/cats/american-curl",
      "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/american-curl",
      "temperament": "Affectionate, Curious, Intelligent, Interactive, Lively, Playful, Social",
      "origin": "United States",
      "country_codes": "US",
      "country_code": "US",
      "description": "Distinguished by truly unique ears that curl back in a graceful arc, offering an alert, perky, happily surprised expression, they cause people to break out into a big smile when viewing their first Curl. Curls are very people-oriented, faithful, affectionate soulmates, adjusting remarkably fast to other pets, children, and new situations.",
      "life_span": "12 - 16",
      "indoor": 0,
      "lap": 1,
      "alt_names": "",
      "adaptability": 5,
      "affection_level": 5,
      "child_friendly": 4,
      "dog_friendly": 5,
      "energy_level": 3,
      "grooming": 2,
      "health_issues": 1,
      "intelligence": 3,
      "shedding_level": 3,
      "social_needs": 3,
      "stranger_friendly": 3,
      "vocalisation": 3,
      "experimental": 0,
      "hairless": 0,
      "natural": 0,
      "rare": 0,
      "rex": 0,
      "suppressed_tail": 0,
      "short_legs": 0,
      "wikipedia_url": "https://en.wikipedia.org/wiki/American_Curl",
      "hypoallergenic": 0,
      "reference_image_id": "xnsqonbjW"
    }
  ],
  "id": "ji-5E0VwY",
  "url": "https://cdn2.thecatapi.com/images/ji-5E0VwY.jpg",
  "width": 1250,
  "height": 702
}, {
  "breeds": [
    {
      "weight": {
        "imperial": "8 - 18",
        "metric": "4 - 8"
      },
      "id": "bslo",
      "name": "British Longhair",
      "temperament": "Affectionate, Easy Going, Independent, Intelligent, Loyal, Social",
      "origin": "United Kingdom",
      "country_codes": "GB",
      "country_code": "GB",
      "description": "The British Longhair is a very laid-back relaxed cat, often perceived to be very independent although they will enjoy the company of an equally relaxed and likeminded cat. They are an affectionate breed, but very much on their own terms and tend to prefer to choose to come and sit with their owners rather than being picked up.",
      "life_span": "12 - 14",
      "indoor": 0,
      "alt_names": "",
      "adaptability": 5,
      "affection_level": 5,
      "child_friendly": 4,
      "dog_friendly": 5,
      "energy_level": 4,
      "grooming": 5,
      "health_issues": 1,
      "intelligence": 5,
      "shedding_level": 1,
      "social_needs": 3,
      "stranger_friendly": 4,
      "vocalisation": 1,
      "experimental": 0,
      "hairless": 0,
      "natural": 0,
      "rare": 0,
      "rex": 0,
      "suppressed_tail": 0,
      "short_legs": 0,
      "wikipedia_url": "https://en.wikipedia.org/wiki/British_Longhair",
      "hypoallergenic": 0,
      "reference_image_id": "7isAO4Cav"
    }
  ],
  "id": "re7uO34hz",
  "url": "https://cdn2.thecatapi.com/images/re7uO34hz.jpg",
  "width": 1600,
  "height": 2397
}];

export const breeds = [{
  "weight": {
    "imperial": "6 - 12",
    "metric": "3 - 5"
  },
  "id": "sphy",
  "name": "Sphynx",
  "cfa_url": "http://cfa.org/Breeds/BreedsSthruT/Sphynx.aspx",
  "vetstreet_url": "http://www.vetstreet.com/cats/sphynx",
  "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/sphynx",
  "temperament": "Loyal, Inquisitive, Friendly, Quiet, Gentle",
  "origin": "Canada",
  "country_codes": "CA",
  "country_code": "CA",
  "description": "The Sphynx is an intelligent, inquisitive, extremely friendly people-oriented breed. Sphynx commonly greet their owners  at the front door, with obvious excitement and happiness. She has an unexpected sense of humor that is often at odds with her dour expression.",
  "life_span": "12 - 14",
  "indoor": 0,
  "lap": 1,
  "alt_names": "Canadian Hairless, Canadian Sphynx",
  "adaptability": 5,
  "affection_level": 5,
  "child_friendly": 4,
  "dog_friendly": 5,
  "energy_level": 3,
  "grooming": 2,
  "health_issues": 4,
  "intelligence": 5,
  "shedding_level": 1,
  "social_needs": 5,
  "stranger_friendly": 5,
  "vocalisation": 5,
  "experimental": 0,
  "hairless": 1,
  "natural": 0,
  "rare": 1,
  "rex": 0,
  "suppressed_tail": 0,
  "short_legs": 0,
  "wikipedia_url": "https://en.wikipedia.org/wiki/Sphynx_(cat)",
  "hypoallergenic": 1,
  "reference_image_id": "BDb8ZXb1v"
},
{
  "weight": {
    "imperial": "6 - 12",
    "metric": "3 - 5"
  },
  "id": "tonk",
  "name": "Tonkinese",
  "cfa_url": "http://cfa.org/Breeds/BreedsSthruT/Tonkinese.aspx",
  "vetstreet_url": "http://www.vetstreet.com/cats/tonkinese",
  "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/tonkinese",
  "temperament": "Curious, Intelligent, Social, Lively, Outgoing, Playful, Affectionate",
  "origin": "Canada",
  "country_codes": "CA",
  "country_code": "CA",
  "description": "Intelligent and generous with their affection, a Tonkinese will supervise all activities with curiosity. Loving, social, active, playful, yet content to be a lap cat",
  "life_span": "14 - 16",
  "indoor": 0,
  "lap": 1,
  "alt_names": "Tonk",
  "adaptability": 5,
  "affection_level": 5,
  "child_friendly": 4,
  "dog_friendly": 5,
  "energy_level": 5,
  "grooming": 1,
  "health_issues": 1,
  "intelligence": 5,
  "shedding_level": 3,
  "social_needs": 5,
  "stranger_friendly": 5,
  "vocalisation": 5,
  "experimental": 0,
  "hairless": 0,
  "natural": 0,
  "rare": 0,
  "rex": 0,
  "suppressed_tail": 0,
  "short_legs": 0,
  "wikipedia_url": "https://en.wikipedia.org/wiki/Tonkinese_(cat)",
  "hypoallergenic": 0,
  "reference_image_id": "KBroiVNCM"
},
{
  "weight": {
    "imperial": "7 - 15",
    "metric": "3 - 7"
  },
  "id": "toyg",
  "name": "Toyger",
  "vetstreet_url": "http://www.vetstreet.com/cats/toyger",
  "temperament": "Playful, Social, Intelligent",
  "origin": "United States",
  "country_codes": "US",
  "country_code": "US",
  "description": "The Toyger has a sweet, calm personality and is generally friendly. He's outgoing enough to walk on a leash, energetic enough to play fetch and other interactive games, and confident enough to get along with other cats and friendly dogs.",
  "life_span": "12 - 15",
  "indoor": 0,
  "lap": 1,
  "alt_names": "",
  "adaptability": 5,
  "affection_level": 5,
  "child_friendly": 4,
  "dog_friendly": 5,
  "energy_level": 5,
  "grooming": 1,
  "health_issues": 2,
  "intelligence": 5,
  "shedding_level": 3,
  "social_needs": 3,
  "stranger_friendly": 5,
  "vocalisation": 5,
  "experimental": 0,
  "hairless": 0,
  "natural": 0,
  "rare": 0,
  "rex": 0,
  "suppressed_tail": 0,
  "short_legs": 0,
  "wikipedia_url": "https://en.wikipedia.org/wiki/Toyger",
  "hypoallergenic": 0,
  "reference_image_id": "O3F3_S1XN"
},
{
  "weight": {
    "imperial": "5 - 10",
    "metric": "2 - 5"
  },
  "id": "tang",
  "name": "Turkish Angora",
  "cfa_url": "http://cfa.org/Breeds/BreedsSthruT/TurkishAngora.aspx",
  "vetstreet_url": "http://www.vetstreet.com/cats/turkish-angora",
  "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/turkish-angora",
  "temperament": "Affectionate, Agile, Clever, Gentle, Intelligent, Playful, Social",
  "origin": "Turkey",
  "country_codes": "TR",
  "country_code": "TR",
  "description": "This is a smart and intelligent cat which bonds well with humans. With its affectionate and playful personality the Angora is a top choice for families. The Angora gets along great with other pets in the home, but it will make clear who is in charge, and who the house belongs to",
  "life_span": "15 - 18",
  "indoor": 0,
  "alt_names": "Ankara",
  "adaptability": 5,
  "affection_level": 5,
  "child_friendly": 4,
  "dog_friendly": 5,
  "energy_level": 5,
  "grooming": 2,
  "health_issues": 2,
  "intelligence": 5,
  "shedding_level": 2,
  "social_needs": 5,
  "stranger_friendly": 5,
  "vocalisation": 3,
  "experimental": 0,
  "hairless": 0,
  "natural": 1,
  "rare": 0,
  "rex": 0,
  "suppressed_tail": 0,
  "short_legs": 0,
  "wikipedia_url": "https://en.wikipedia.org/wiki/Turkish_Angora",
  "hypoallergenic": 0,
  "reference_image_id": "7CGV6WVXq"
},
{
  "weight": {
    "imperial": "7 - 20",
    "metric": "3 - 9"
  },
  "id": "tvan",
  "name": "Turkish Van",
  "cfa_url": "http://cfa.org/Breeds/BreedsSthruT/TurkishVan.aspx",
  "vetstreet_url": "http://www.vetstreet.com/cats/turkish-van",
  "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/turkish-van",
  "temperament": "Agile, Intelligent, Loyal, Playful, Energetic",
  "origin": "Turkey",
  "country_codes": "TR",
  "country_code": "TR",
  "description": "While the Turkish Van loves to jump and climb, play with toys, retrieve and play chase, she is is big and ungainly; this is one cat who doesn’t always land on his feet. While not much of a lap cat, the Van will be happy to cuddle next to you and sleep in your bed. ",
  "life_span": "12 - 17",
  "indoor": 0,
  "alt_names": "Turkish Cat, Swimming cat",
  "adaptability": 5,
  "affection_level": 5,
  "child_friendly": 4,
  "dog_friendly": 5,
  "energy_level": 5,
  "grooming": 2,
  "health_issues": 1,
  "intelligence": 5,
  "shedding_level": 3,
  "social_needs": 4,
  "stranger_friendly": 4,
  "vocalisation": 5,
  "experimental": 0,
  "hairless": 0,
  "natural": 1,
  "rare": 0,
  "rex": 0,
  "suppressed_tail": 0,
  "short_legs": 0,
  "wikipedia_url": "https://en.wikipedia.org/wiki/Turkish_Van",
  "hypoallergenic": 0,
  "reference_image_id": "sxIXJax6h"
},
{
  "weight": {
    "imperial": "12 - 18",
    "metric": "5 - 8"
  },
  "id": "ycho",
  "name": "York Chocolate",
  "temperament": "Playful, Social, Intelligent, Curious, Friendly",
  "origin": "United States",
  "country_codes": "US",
  "country_code": "US",
  "description": "York Chocolate cats are known to be true lap cats with a sweet temperament. They love to be cuddled and petted. Their curious nature makes them follow you all the time and participate in almost everything you do, even if it's related to water: unlike many other cats, York Chocolates love it.",
  "life_span": "13 - 15",
  "indoor": 0,
  "lap": 1,
  "alt_names": "York",
  "adaptability": 5,
  "affection_level": 5,
  "child_friendly": 4,
  "dog_friendly": 5,
  "energy_level": 5,
  "grooming": 3,
  "health_issues": 1,
  "intelligence": 5,
  "shedding_level": 3,
  "social_needs": 4,
  "stranger_friendly": 4,
  "vocalisation": 5,
  "experimental": 0,
  "hairless": 0,
  "natural": 0,
  "rare": 0,
  "rex": 0,
  "suppressed_tail": 0,
  "short_legs": 0,
  "wikipedia_url": "https://en.wikipedia.org/wiki/York_Chocolate",
  "hypoallergenic": 0,
  "reference_image_id": "0SxW2SQ_S"
}];

export const breedDetails = [{
  "breeds": [
    {
      "weight": {
        "imperial": "6 - 12",
        "metric": "3 - 7"
      },
      "id": "beng",
      "name": "Bengal",
      "cfa_url": "http://cfa.org/Breeds/BreedsAB/Bengal.aspx",
      "vetstreet_url": "http://www.vetstreet.com/cats/bengal",
      "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/bengal",
      "temperament": "Alert, Agile, Energetic, Demanding, Intelligent",
      "origin": "United States",
      "country_codes": "US",
      "country_code": "US",
      "description": "Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
      "life_span": "12 - 15",
      "indoor": 0,
      "lap": 0,
      "adaptability": 5,
      "affection_level": 5,
      "child_friendly": 4,
      "cat_friendly": 4,
      "dog_friendly": 5,
      "energy_level": 5,
      "grooming": 1,
      "health_issues": 3,
      "intelligence": 5,
      "shedding_level": 3,
      "social_needs": 5,
      "stranger_friendly": 3,
      "vocalisation": 5,
      "bidability": 3,
      "experimental": 0,
      "hairless": 0,
      "natural": 0,
      "rare": 0,
      "rex": 0,
      "suppressed_tail": 0,
      "short_legs": 0,
      "wikipedia_url": "https://en.wikipedia.org/wiki/Bengal_(cat)",
      "hypoallergenic": 1,
      "reference_image_id": "O3btzLlsO"
    }
  ],
  "id": "O3btzLlsO",
  "url": "https://cdn2.thecatapi.com/images/O3btzLlsO.png",
  "width": 1100,
  "height": 739
},
{
  "breeds": [
    {
      "weight": {
        "imperial": "6 - 12",
        "metric": "3 - 7"
      },
      "id": "beng",
      "name": "Bengal",
      "cfa_url": "http://cfa.org/Breeds/BreedsAB/Bengal.aspx",
      "vetstreet_url": "http://www.vetstreet.com/cats/bengal",
      "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/bengal",
      "temperament": "Alert, Agile, Energetic, Demanding, Intelligent",
      "origin": "United States",
      "country_codes": "US",
      "country_code": "US",
      "description": "Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
      "life_span": "12 - 15",
      "indoor": 0,
      "lap": 0,
      "adaptability": 5,
      "affection_level": 5,
      "child_friendly": 4,
      "cat_friendly": 4,
      "dog_friendly": 5,
      "energy_level": 5,
      "grooming": 1,
      "health_issues": 3,
      "intelligence": 5,
      "shedding_level": 3,
      "social_needs": 5,
      "stranger_friendly": 3,
      "vocalisation": 5,
      "bidability": 3,
      "experimental": 0,
      "hairless": 0,
      "natural": 0,
      "rare": 0,
      "rex": 0,
      "suppressed_tail": 0,
      "short_legs": 0,
      "wikipedia_url": "https://en.wikipedia.org/wiki/Bengal_(cat)",
      "hypoallergenic": 1,
      "reference_image_id": "O3btzLlsO"
    }
  ],
  "id": "udZiLDG_E",
  "url": "https://cdn2.thecatapi.com/images/udZiLDG_E.jpg",
  "width": 880,
  "height": 1100
},
{
  "breeds": [
    {
      "weight": {
        "imperial": "6 - 12",
        "metric": "3 - 7"
      },
      "id": "beng",
      "name": "Bengal",
      "cfa_url": "http://cfa.org/Breeds/BreedsAB/Bengal.aspx",
      "vetstreet_url": "http://www.vetstreet.com/cats/bengal",
      "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/bengal",
      "temperament": "Alert, Agile, Energetic, Demanding, Intelligent",
      "origin": "United States",
      "country_codes": "US",
      "country_code": "US",
      "description": "Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
      "life_span": "12 - 15",
      "indoor": 0,
      "lap": 0,
      "adaptability": 5,
      "affection_level": 5,
      "child_friendly": 4,
      "cat_friendly": 4,
      "dog_friendly": 5,
      "energy_level": 5,
      "grooming": 1,
      "health_issues": 3,
      "intelligence": 5,
      "shedding_level": 3,
      "social_needs": 5,
      "stranger_friendly": 3,
      "vocalisation": 5,
      "bidability": 3,
      "experimental": 0,
      "hairless": 0,
      "natural": 0,
      "rare": 0,
      "rex": 0,
      "suppressed_tail": 0,
      "short_legs": 0,
      "wikipedia_url": "https://en.wikipedia.org/wiki/Bengal_(cat)",
      "hypoallergenic": 1,
      "reference_image_id": "O3btzLlsO"
    }
  ],
  "id": "sPMOo3Jn2",
  "url": "https://cdn2.thecatapi.com/images/sPMOo3Jn2.jpg",
  "width": 880,
  "height": 1100
}];

export const favourites = [{
  "id": 101318812,
  "user_id": "w2yqnb",
  "image_id": "S97Qj5YYO",
  "sub_id": "draviolo",
  "created_at": "2023-04-05T16:44:23.000Z",
  "image": {
    "id": "S97Qj5YYO",
    "url": "https://cdn2.thecatapi.com/images/S97Qj5YYO.jpg"
  }
},
{
  "id": 101318813,
  "user_id": "w2yqnb",
  "image_id": "ji-5E0VwY",
  "sub_id": "draviolo",
  "created_at": "2023-04-05T16:45:28.000Z",
  "image": {
    "id": "ji-5E0VwY",
    "url": "https://cdn2.thecatapi.com/images/ji-5E0VwY.jpg"
  }
},
{
  "id": 101318814,
  "user_id": "w2yqnb",
  "image_id": "DFHMMPNcD",
  "sub_id": "draviolo",
  "created_at": "2023-04-05T16:55:43.000Z",
  "image": {
    "id": "DFHMMPNcD",
    "url": "https://cdn2.thecatapi.com/images/DFHMMPNcD.jpg"
  }
},
{
  "id": 101318815,
  "user_id": "w2yqnb",
  "image_id": "J4Jv10E7O",
  "sub_id": "draviolo",
  "created_at": "2023-04-05T17:03:16.000Z",
  "image": {
    "id": "J4Jv10E7O",
    "url": "https://cdn2.thecatapi.com/images/J4Jv10E7O.jpg"
  }
},
{
  "id": 101318839,
  "user_id": "w2yqnb",
  "image_id": "QAWwhRFCG",
  "sub_id": "draviolo",
  "created_at": "2023-04-05T17:19:51.000Z",
  "image": {
    "id": "QAWwhRFCG",
    "url": "https://cdn2.thecatapi.com/images/QAWwhRFCG.jpg"
  }
},
{
  "id": 101318848,
  "user_id": "w2yqnb",
  "image_id": "dVujvBqnu",
  "sub_id": "draviolo",
  "created_at": "2023-04-05T17:45:00.000Z",
  "image": {
    "id": "dVujvBqnu",
    "url": "https://cdn2.thecatapi.com/images/dVujvBqnu.jpg"
  }
},
{
  "id": 101318851,
  "user_id": "w2yqnb",
  "image_id": "_PEqOH17A",
  "sub_id": "draviolo",
  "created_at": "2023-04-05T18:44:32.000Z",
  "image": {
    "id": "_PEqOH17A",
    "url": "https://cdn2.thecatapi.com/images/_PEqOH17A.jpg"
  }
},
{
  "id": 101318888,
  "user_id": "w2yqnb",
  "image_id": "86jwAC0vv",
  "sub_id": "draviolo",
  "created_at": "2023-04-05T20:45:14.000Z",
  "image": {
    "id": "86jwAC0vv",
    "url": "https://cdn2.thecatapi.com/images/86jwAC0vv.jpg"
  }
},
{
  "id": 101319248,
  "user_id": "w2yqnb",
  "image_id": "3FoFgV7R2",
  "sub_id": "draviolo",
  "created_at": "2023-04-06T12:07:59.000Z",
  "image": {
    "id": "3FoFgV7R2",
    "url": "https://cdn2.thecatapi.com/images/3FoFgV7R2.jpg"
  }
},
{
  "id": 101319251,
  "user_id": "w2yqnb",
  "image_id": "NuSl1fmU9",
  "sub_id": "draviolo",
  "created_at": "2023-04-06T12:44:33.000Z",
  "image": {
    "id": "NuSl1fmU9",
    "url": "https://cdn2.thecatapi.com/images/NuSl1fmU9.jpg"
  }
}];
